### PR TITLE
School Request: University of Mines and Technology

### PR DESCRIPTION
**Pull request by fredabila**

### CODE REVIEW

**Comment by fredabila** [comment]
Please does this normally take this long or i have to wait. I'm wondering if i did something wrong

**Comment by blackmann** [comment]
Hi @fredabila 

This is not an automated process.

I'll get to it as soon I can.

**Review by blackmann — APPROVED** [review]

**Comment by fredabila** [comment]
I was trying to find an IP section in railway but I couldn't instead I tried this. Would it be possible to get the domain Umat.compa.so

**Comment by blackmann** [comment]
Umat has been deployed: https://umat.compa.so

**Comment by fredabila** [comment]
Oh okay. Please is there any documentation I could follow to guide in usage of this platform

**Pull request merged**
