### PR TITLE
moved favicon from client to website/public

### PR DESCRIPTION
**Pull request by avi-l**
dev.db-journal was created when I started the app.

### CODE REVIEW

**Comment by avi-l** [comment]
> dev.db-journal was created when I started the app.

removed via app

**Comment by blackmann** [comment]
Could you add the db journal to gitignore with this PR? So it saves us in future

**Comment by avi-l** [comment]
done. really .env should be in .gitignore also. if what you have in there
is not sensitive then should just be in a consts export file or something
like that

**Comment by avi-l** [comment]
oh i just read the .env file comments, it's from prisma. but still.

**Comment by blackmann** [comment]
The .env is not used in prod. Remix doesn't use it (by default).

It's there for reference sake 

No need to add to gitignore

**Pull request merged**
